application:
  name: django-app
  namespace: default
  repoURL: https://github.com/daria-hk/goit-devops.git
  path: charts/django-app
  targetRevision: main
  autoSync: true
  prune: true
  selfHeal: true
