apiVersion: v1
kind: Secret
metadata:
  name: django-secret
type: Opaque
data:
  DJANGO_SECRET_KEY: {{ .Values.secrets.DJANGO_SECRET_KEY | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.secrets.POSTGRES_PASSWORD | b64enc }}
